[2024-05-31T15:10:03.310+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_csv_files.combine_files manual__2024-05-31T15:09:59.058379+00:00 [queued]>
[2024-05-31T15:10:03.314+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_csv_files.combine_files manual__2024-05-31T15:09:59.058379+00:00 [queued]>
[2024-05-31T15:10:03.314+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-05-31T15:10:03.320+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): combine_files> on 2024-05-31 15:09:59.058379+00:00
[2024-05-31T15:10:03.323+0000] {standard_task_runner.py:60} INFO - Started process 320 to run task
[2024-05-31T15:10:03.324+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'etl_csv_files', 'combine_files', 'manual__2024-05-31T15:09:59.058379+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/etl_from_csv.py', '--cfg-path', '/tmp/tmpk6d_z75f']
[2024-05-31T15:10:03.325+0000] {standard_task_runner.py:88} INFO - Job 13: Subtask combine_files
[2024-05-31T15:10:03.345+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_csv_files.combine_files manual__2024-05-31T15:09:59.058379+00:00 [running]> on host 720c72730b57
[2024-05-31T15:10:03.380+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_csv_files' AIRFLOW_CTX_TASK_ID='combine_files' AIRFLOW_CTX_EXECUTION_DATE='2024-05-31T15:09:59.058379+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-31T15:09:59.058379+00:00'
[2024-05-31T15:10:03.390+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_from_csv.py", line 57, in combine_files
    df = df_customer.set_index('customer_id').join(df_purchase.set_index('customer_id'), how='inner').reset_index()
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 9729, in join
    return self._join_compat(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 9768, in _join_compat
    return merge(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 162, in merge
    return op.get_result(copy=copy)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 811, in get_result
    result = self._reindex_and_concat(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 763, in _reindex_and_concat
    llabels, rlabels = _items_overlap_with_suffix(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 2604, in _items_overlap_with_suffix
    raise ValueError(f"columns overlap but no suffix specified: {to_rename}")
ValueError: columns overlap but no suffix specified: Index(['page_views', 'time_spent'], dtype='object')
[2024-05-31T15:10:03.396+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=etl_csv_files, task_id=combine_files, execution_date=20240531T150959, start_date=20240531T151003, end_date=20240531T151003
[2024-05-31T15:10:03.402+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 13 for task combine_files (columns overlap but no suffix specified: Index(['page_views', 'time_spent'], dtype='object'); 320)
[2024-05-31T15:10:03.424+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-31T15:10:03.436+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
